version: '3'

tasks:
  default:
    desc: show commands
    cmds:
      - task -l --sort none

  build:
    desc: build the container
    cmds:
      - docker compose build --no-cache --force-rm

  up:
    desc: start the container
    cmds:
      - docker compose up --watch --menu=false

  stop:
    desc: stop the container
    cmds:
      - docker compose stop

  down:
    desc: down the container
    cmds:
      - docker compose down --remove-orphans

  down-v:
    desc: down the container and volume
    cmds:
      - docker compose down --remove-orphans --volume

  destroy:
    desc: destroy the all image and volume
    cmds:
      - docker compose down --rmi all --volumes --remove-orphans

  ps:
    desc: ps the container
    cmds:
      - docker compose ps

  logs:
    desc: show docker logs
    cmds:
      - docker compose logs

  watch-logs:
    desc: watch docker logs
    cmds:
      - docker compose logs --follow

  logs-app:
    desc: show backend logs
    cmds:
      - docker compose logs app

  dev:
    desc: start development environment
    cmds:
      - echo "🚀 Starting Koog Examples development environment..."
      - docker compose up --watch --menu=false

  test:
    desc: run tests
    cmds:
      - docker compose exec app ./gradlew test

  clean:
    desc: clean build artifacts
    cmds:
      - docker compose exec app ./gradlew clean

  shell:
    desc: open shell in app container
    cmds:
      - docker compose exec app /bin/bash

  gradle:
    desc: run gradle command (usage task gradle -- bootRun)
    cmds:
      - docker compose exec app ./gradlew {{.CLI_ARGS}}
