spring:
  application:
    name: koog-examples
  profiles:
    active: ${APP_ENV:dev}
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

# koog-spring-boot-starterを利用しているが、googleExecutorでAPIKeyがうまく渡されおらずOAUTH2の認証になってしまい403エラーになってしまう
# ただ、この設定をかかないとビルドエラーになってしまうので、一旦記載している
ai:
  koog:
    google:
      api-key: ${GOOGLE_API_KEY:}

logging:
  level:
    root: ${LOG_LEVEL:INFO}
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

agent:
  model: ${AGENT_MODEL:gemini-2.0-flash-001}
  system-prompt: ${AGENT_SYSTEM_PROMPT:You are a helpful assistant. Please respond in Japanese.}

phase2:
  model: ${PHASE2_MODEL:gemini-2.0-flash-001}
  system-prompt: ${PHASE2_SYSTEM_PROMPT:あなたは様々なツールを使いこなす有能なアシスタントです。ユーザーの要求に応じて適切なツールを選択し、実行してください。}
  max-tokens: ${PHASE2_MAX_TOKENS:2048}
  temperature: ${PHASE2_TEMPERATURE:0.7}

api:
  openweather-api-key: ${OPENWEATHER_API_KEY:}
  news-api-key: ${NEWS_API_KEY:}
  openweather-base-url: ${API_OPENWEATHER_BASE_URL:https://api.openweathermap.org/data/2.5}
  news-api-base-url: ${API_NEWS_API_BASE_URL:https://newsapi.org/v2}
  request-timeout: ${API_REQUEST_TIMEOUT:30000}
  max-retries: ${API_MAX_RETRIES:3}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
